[project]
name = "module-creator-installer"
version = "0.0.1"
description = "Python / Rust manager"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bump2version>=1.0.1",
    "pyside6>=6.9.0",
    "toml>=0.10.2",
]
