[project]
name = "module-creator-installer"
version = "0.1.0"
description = "Python / Rust manager"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.9.0",
    "toml>=0.10.2",
]
